# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTaTopicOption',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('option_name', models.CharField(max_length=2400)),
                ('option_type', models.CharField(max_length=2400)),
                ('option_attrs', jsonfield.fields.JSONField()),
                ('ta_topic_id', models.CharField(max_length=8)),
                ('ta_topic_relevance', models.PositiveSmallIntegerField()),
                ('topic_id', models.CharField(max_length=8)),
                ('client_id', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchEa',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('attrs', jsonfield.fields.JSONField()),
                ('score_attrs', jsonfield.fields.JSONField()),
                ('client_id', models.CharField(max_length=8)),
                ('batch_id', models.CharField(max_length=8)),
                ('counter', models.PositiveIntegerField()),
                ('prospect_id', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientLookupForEa',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('ta_attrs', jsonfield.fields.JSONField()),
                ('ta_topics', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveredEa',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=2400)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=2400)),
                ('url', models.CharField(max_length=2400)),
                ('score', models.DecimalField(decimal_places=7, max_digits=19)),
                ('batch_id', models.CharField(max_length=8)),
                ('score_attrs', jsonfield.fields.JSONField()),
                ('assigned_entities', jsonfield.fields.JSONField()),
                ('prospect_id', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EoLookupByProvider',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('external_id', models.CharField(max_length=2400)),
                ('provider_type', models.CharField(max_length=2400)),
                ('prospect_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='EoLookupForEa',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('eo_attrs', jsonfield.fields.JSONField()),
                ('topic_ids', jsonfield.fields.JSONField(default=list)),
                ('provider_type', models.CharField(max_length=2400)),
                ('profile_id', models.CharField(max_length=8)),
                ('prospect_id', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileLookupByProvider',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('external_id', models.CharField(max_length=2400)),
                ('provider_type', models.CharField(max_length=2400)),
                ('prospect_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLookupForEa',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('profile_attrs', jsonfield.fields.JSONField()),
                ('prospect_id', models.CharField(max_length=8)),
                ('provider_type', models.CharField(max_length=2400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProspectLookupForEa',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('attrs', jsonfield.fields.JSONField()),
                ('topic_ids', jsonfield.fields.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicLookup',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=2400)),
                ('stem', models.CharField(max_length=2400)),
                ('collapsed_stem', models.CharField(max_length=2400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='profilelookupbyprovider',
            unique_together=set([('external_id', 'provider_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='eolookupbyprovider',
            unique_together=set([('external_id', 'provider_type', 'prospect_id')]),
        ),
    ]
