# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgreementAlert',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('outcome_alert_date', models.DateTimeField(blank=True, null=True)),
                ('outcome_alert_enabled', models.BooleanField()),
                ('outcome_alert_created', models.BooleanField()),
                ('outcome_notice_alert_date', models.DateTimeField(blank=True, null=True)),
                ('outcome_notice_alert_enabled', models.BooleanField()),
                ('outcome_notice_alert_created', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgreementSearch',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=2400)),
                ('user_id', models.CharField(max_length=8)),
                ('counterparty', models.CharField(blank=True, max_length=2400, null=True)),
                ('agreement_type_id', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgreementTypeLookup',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=2400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetLookup',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=2400)),
                ('path', models.CharField(max_length=2400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalAgreementType',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=2400)),
                ('system_created_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAgreementType',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=2400)),
                ('user_id', models.CharField(max_length=8)),
                ('system_created_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
